"""empty message

Revision ID: b334e4d81458
Revises: 
Create Date: 2022-12-07 13:17:35.103427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b334e4d81458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('email_validate', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('registration_timestamp', sa.DateTime(), nullable=True),
    sa.Column('visiting_timestamp', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('sending_recommendations', sa.Boolean(), nullable=True),
    sa.Column('sending_messages', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_model_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_model_username'), ['username'], unique=True)

    op.create_table('city_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('personal_items_clothes_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('photo_list', sa.PickleType(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('stop_timestamp', sa.DateTime(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('deleted_status', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('clothes_type', sa.String(length=32), nullable=True),
    sa.Column('clothes_season', sa.String(length=32), nullable=True),
    sa.Column('clothes_sex', sa.String(length=16), nullable=True),
    sa.Column('clothes_size', sa.String(length=8), nullable=True),
    sa.Column('clothes_status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_model.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country_model.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_items_clothes_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_items_clothes_model_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_items_clothes_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_items_clothes_model_title'))

    op.drop_table('personal_items_clothes_model')
    op.drop_table('city_model')
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_username'))
        batch_op.drop_index(batch_op.f('ix_user_model_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_model_email'))

    op.drop_table('user_model')
    op.drop_table('country_model')
    # ### end Alembic commands ###
